[package]
name = "ic_siwe_provider"
version = "0.0.6"
edition = "2021"
authors = ["Kristofer Lund <kristofer@kristoferlund.se>"]
description = "Using the pre built ic_siwe_provider canister is the easiest way to integrate Ethereum wallet authentication into an Internet Computer (ICP) application."
license = "MIT"
homepage = "https://github.com/kristoferlund/ic-siwe"
repository = "https://github.com/kristoferlund/ic-siwe"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.9.11"
ic-cdk = "0.11.3"
ic_siwe = { path = "../ic_siwe" }
ic-stable-structures = "0.6.0"
ic-certified-map = "0.4.0"
serde = "1.0.193"
serde_json = "1.0.108"
serde_bytes = "0.11"
num-traits = "0.2.18"

[dev-dependencies]
# ethers = "2.0.10"
hex = "0.4.3"
ic-agent = "0.29.0"
pocket-ic = "2.0.1"
# siwe = "0.6"
rand = "0.8.4"
ring = "0.16.20"
zeroize = { version = "1.3", default-features = false }
bs58 = "0.5.1"
solana-sdk = "1.18.8"
